[package]
edition = "2021"
name = "fukomaster"
version = "0.1.0"

[dependencies]
# uinput = "0.1.3"
# evdev = "0.12.2"
anyhow = "1.0.86"
evdev-rs = { version = "0.6.1", features = ["libevdev-1-10"] }
